Added validation for "Invalid updating of role with empty data", Still debugging integration_test.py
AssertionError: {'description': 'A Project Manager manages a[68 chars]ger'} !=